name: Build Firmware

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_firmware:
    runs-on: ubuntu-latest
    container:
      image: docker.io/kvasirio/rp2350:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Configure git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build firmware
        run: ./scripts/build.sh

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            docker_build/*.bin
            docker_build/*.hex
            docker_build/*.elf
            docker_build/*.uf2
            docker_build/*.lst
            docker_build/*.map

  release:
    runs-on: ubuntu-latest
    needs: build_firmware
    if: github.ref == 'refs/heads/master'

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: download firmware
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: build

      - name: zip firmware
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r firmware.zip build

      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: firmware.zip
          tag: build-${{ github.run_number }}-${{ github.sha }}
          name: Build ${{ github.run_number }} (${{ github.sha }})
          body: |
            Automated build from commit ${{ github.sha }}
            Run number: ${{ github.run_number }}
            Commit: ${{ github.event.head_commit.message }}
          prerelease: true
