name: Build Firmware

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_firmware:
    runs-on: ubuntu-latest
    container:
      image: docker.io/kvasirio/rp2350:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Configure git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build firmware
        run: ./scripts/build.sh

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            docker_build/*.bin
            docker_build/*.hex
            docker_build/*.elf
            docker_build/*.uf2
            docker_build/*.lst
            docker_build/*.map

  release:
    runs-on: ubuntu-latest
    needs: build_firmware
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download firmware
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: build

      - name: Create release with GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_NAME="build-$(date +%Y%m%d-%H%M%S)-${GITHUB_SHA:0:7}"
          gh release create "$RELEASE_NAME" \
            --title "Build $RELEASE_NAME" \
            --notes "Automated build from commit ${GITHUB_SHA:0:7}" \
            --prerelease \
            build/*.bin build/*.hex build/*.elf build/*.uf2 build/*.lst build/*.map
